### ISSUE TITLE
Failure when pressing record/upload too quickly

### ISSUE THREAD

**Issue by migurski** [codeforamerica/cityvoice-survey-builder#87]
We get an internal server error at the tarball step when pressing upload/record too quickly, for example when rushing through the builder as a test.

**Comment by migurski** [comment]
This might be the error:

```
2015-08-14T23:12:27.296353+00:00 app[web.1]: JSON::ParserError - 757: unexpected token at 'null':*******************        
2015-08-14T23:12:27.296358+00:00 app[web.1]:   1/app/vendor/ruby-2.1.1/lib/ruby/2.1.0/json/common.rb:155:in `parse'         
2015-08-14T23:12:27.296362+00:00 app[web.1]: 320/app/cityvoice_builder_heroku.rb:182:in `block in <class:CityvoiceBuilderHeroku>'
2015-08-14T23:12:27.296360+00:00 app[web.1]:  96/app/vendor/ruby-2.1.1/lib/ruby/2.1.0/json/common.rb:155:in `parse'         
2015-08-14T23:12:27.296378+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2015-08-14T23:12:27.296380+00:00 app[web.1]: 128/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2015-08-14T23:12:27.296381+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2015-08-14T23:12:27.296383+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2015-08-14T23:12:27.296384+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2015-08-14T23:12:27.296386+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2015-08-14T23:12:27.296387+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2015-08-14T23:12:27.296388+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
2015-08-14T23:12:27.296390+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
2015-08-14T23:12:27.296391+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
2015-08-14T23:12:27.296393+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
2015-08-14T23:12:27.296392+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2015-08-14T23:12:27.296395+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
2015-08-14T23:12:27.296396+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-08-14T23:12:27.296399+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-08-14T23:12:27.296397+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-08-14T23:12:27.296400+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
2015-08-14T23:12:27.296401+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
2015-08-14T23:12:27.296404+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2015-08-14T23:12:27.296403+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2015-08-14T23:12:27.296406+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
2015-08-14T23:12:27.296405+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2015-08-14T23:12:27.296409+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2015-08-14T23:12:27.296410+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-08-14T23:12:27.296407+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
2015-08-14T23:12:27.296411+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-08-14T23:12:27.296412+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2015-08-14T23:12:27.296413+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2015-08-14T23:12:27.296421+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-08-14T23:12:27.296420+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-08-14T23:12:27.296422+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2015-08-14T23:12:27.296424+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
2015-08-14T23:12:27.296425+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
2015-08-14T23:12:27.296428+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
2015-08-14T23:12:27.296430+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
2015-08-14T23:12:27.296426+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
2015-08-14T23:12:27.296427+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2015-08-14T23:12:27.296431+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
2015-08-14T23:12:27.296432+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
2015-08-14T23:12:27.296434+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
2015-08-14T23:12:27.296435+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
2015-08-14T23:12:27.296479+00:00 app[web.1]: 	/app/vendor/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
2015-08-14T23:12:27.296481+00:00 app[web.1]: 	/app/vendor/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
2015-08-14T23:12:27.296501+00:00 app[web.1]: 	/app/vendor/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```
